## Arnoldi's methods

In [1]:
import LinearAlgebra
const la = LinearAlgebra
MAX_ITER = 100;

In [2]:
A = [4. -1 0 -1 0 0;
     -1 4 -1 0 -1 0;
     0 -1 4. 0 0 -1;
     -1 0 0. 4 -1 0;
     0 -1 0 -1 4 -1;
     0 0 -1 0. -1 4]

b = [0, 5, 0, 6, -2, 6.]

x0 = zeros(size(b));
# m
v = [1., 0, 2, 0, 1, 1];

### Arnoldi
Input: $A\in\mathbb{R}^{n\times n}=[a_1,...,a_n], v\in\mathbb{R}^{n}$ any vector

In [3]:
function arnoldi(A:: Matrix{Float64}, v:: Vector{Float64})
    # input: A
    n, m = size(A)
    V = zeros((n, m + 1))
    H = zeros((m + 1, m))
    V[:, 1] = v/la.norm(v)
    for j = 1:m
        for i = 1:j
            H[i, j] = la.dot(A*V[:, j], V[:, i])
        end
        w = A*V[:, j] - V[:, 1:j]*H[1:j, j]
        H[j+1, j] = la.norm(w)
        if H[j+1, j] == 0.0
            break
        end
        V[:, j+1] = w/H[j+1, j]
    end
    H[1:m, :], V[:, 1:m]
end

arnoldi (generic function with 1 method)

In [4]:
H, V = arnoldi(A, v);
display(H)
display(V)

6×6 Matrix{Float64}:
 3.14286  1.92195  -2.77556e-15  1.3628e-14   -4.20552e-13  2.95582
 1.92195  4.6472    1.18932      1.21569e-14  -3.72813e-13  2.61937
 0.0      1.18932   3.95556      0.812257     -2.72227e-13  1.91409
 0.0      0.0       0.812257     3.67305       0.114091     0.726769
 0.0      0.0       0.0          0.114091      3.58133      0.027598
 0.0      0.0       0.0          0.0           5.08975e-13  3.76061

6×6 Matrix{Float64}:
 0.377964   0.168563    0.289595   -0.585252    0.390312   0.413137
 0.0       -0.786629    0.191845    0.228787    0.540433   0.0436258
 0.755929   0.140469   -0.282287    0.128662    0.2502     0.581096
 0.0       -0.393314    0.0959226  -0.699892   -0.310248  -0.0562773
 0.377964  -0.0280939   0.750937    0.313906   -0.440352   0.692342
 0.377964  -0.421408   -0.475959    0.0140224  -0.45036    0.0850704

### Arnoldi-Modified Gram-Schmidt

In [5]:
function arnoldi_modified(A:: Matrix{Float64}, v:: Vector{Float64})
    n, m = size(A)
    
    V = zeros((n, m + 1))
    H = zeros((m + 1, m))
    
    V[:, 1] = v/la.norm(v)
    for j = 1:m
        w = A*V[:, j]
        for i = 1:j
            H[i, j] = la.dot(w, V[:, i])
            w = w - H[i, j]*V[:, i] 
        end
        H[j+1, j] = la.norm(w)
        if H[j+1, j] < eps()
            break
        end
        V[:, j+1] = w/H[j+1, j]
    end
    # Hm the matrix obtained from \hat Hm
    H[1:m, :], V[:, 1:m]
end

arnoldi_modified (generic function with 1 method)

In [6]:
H, V = arnoldi_modified(A, v);
display(H)
display(V)

6×6 Matrix{Float64}:
 3.14286  1.92195  -2.9976e-15  1.4766e-14   -4.53748e-13   3.40829
 1.92195  4.6472    1.18932     1.39333e-14  -4.19331e-13   3.14904
 0.0      1.18932   3.95556     0.812257     -1.56986e-13   1.1831
 0.0      0.0       0.812257    3.67305       0.114091      0.156279
 0.0      0.0       0.0         0.114091      3.58133      -0.00235184
 0.0      0.0       0.0         0.0           4.76224e-13   3.91318e-5

6×6 Matrix{Float64}:
 0.377964   0.168563    0.289595   -0.585252    0.390312   0.469524
 0.0       -0.786629    0.191845    0.228787    0.540433  -0.136148
 0.755929   0.140469   -0.282287    0.128662    0.2502     0.678409
 0.0       -0.393314    0.0959226  -0.699892   -0.310248  -0.0620126
 0.377964  -0.0280939   0.750937    0.313906   -0.440352   0.523144
 0.377964  -0.421408   -0.475959    0.0140224  -0.45036    0.152467

### Householder Arnoldi

In [7]:
function householder_arnoldi(A:: Matrix{Float64}, v:: Vector{Float64})
    n, m = size(A)
    I = Matrix{Float64}(la.I, n, n)
    V = zeros((m, m))
    H = zeros((m, m + 1))
    Z = zeros((m, m + 1))

    Z[:, 1] = v
    Q = I
    for j=1:m
        # w calculus
        beta = sign(Z[j, j]) * la.norm(Z[j:end, j])
        z = zeros(n)
        for i = 1:n
            if i == j
                z[i] = beta + Z[j, j]
            elseif i > j
                z[i] = Z[i, j]
            end
        end
        w = z / la.norm(z)
        P = I - 2 * w * w'

        # hj-1
        H[:, j] = P * Z[:, j]

        Q = P * Q
        V[:, j] = Q'[:, j] 
        if j <= m
            Z[:, j + 1] = Q * A * V[:, j]
        end
    end
    H[:, m + 1] = Q * A * V[:, m]
    return H[:, 2:end], V
end

householder_arnoldi (generic function with 1 method)

In [8]:
v = [1., 0, 2, 0, 1, 1];
H, V = householder_arnoldi(A, v);
show(IOContext(stdout, :limit => false), "text/plain", H)
display(V)

6×6 Matrix{Float64}:
  3.14286      -1.92195      -4.44089e-16  -8.32667e-17   4.44089e-16  -2.22045e-16
 -1.92195       4.6472        1.18932      -3.60822e-16  -2.22045e-16   2.22045e-16
  1.56125e-17   1.18932       3.95556       0.812257     -1.11022e-16  -4.44089e-16
  6.93889e-17   1.73472e-17   0.812257      3.67305       0.114091      2.98372e-16
  1.73472e-17   1.66533e-16  -7.48099e-17   0.114091      3.58133       5.28466e-14
 -1.11022e-16  -1.11022e-16   2.77556e-17  -1.38778e-17   5.26246e-14   5.0

6×6 Matrix{Float64}:
 -0.377964   0.168563    0.289595   -0.585252    0.390312  -0.5
  0.0       -0.786629    0.191845    0.228787    0.540433  -2.07057e-14
 -0.755929   0.140469   -0.282287    0.128662    0.2502     0.5
  0.0       -0.393314    0.0959226  -0.699892   -0.310248   0.5
 -0.377964  -0.0280939   0.750937    0.313906   -0.440352   1.52656e-14
 -0.377964  -0.421408   -0.475959    0.0140224  -0.45036   -0.5

## Arnoldi’s Method for Linear Systems (FOM)

In [9]:
function FOM(A:: Matrix{Float64}, b:: Vector{Float64}, x0:: Vector{Float64})
    n, m = size(A)
    r0 = b - A*x0
    beta = la.norm(r0)
    V = zeros((m, m+1))
    H = zeros((m+1, m))

    V[:, 1] = r0/beta
    for j=1:m
        w = A*V[:, j]
        for i=1:j
            H[i, j] = la.dot(w, V[:, i])
            w = w - H[i, j]*V[:, i]
        end
        H[j+1, j] = la.norm(w)
        if H[j+1, j] == 0.0
            m = j
            break
        end
        V[:, j+1] = w/H[j+1, j]
    end
    H[1:m, :], V[:, 1:m], beta
end

FOM (generic function with 1 method)

In [10]:
H, V, beta = FOM(A, b, x0)
y = la.inv(H)[:, 1] * beta
x = x0 + V*y

6-element Vector{Float64}:
 0.9999999999999929
 2.000000000000032
 0.9999999999999929
 2.0
 1.0
 2.0

In [11]:
function restarted_FOM(A:: Matrix{Float64}, b:: Vector{Float64}, x0:: Vector{Float64}, tol=1.0e-6)
    n, m = size(A)
    println("x[0] = $x0")
    for i=1:2
        r0 = b - A*x0
        beta = la.norm(r0)
        v = r0/beta

        H, V = householder_arnoldi(A, v)
        y = la.inv(H)[:, 1] * beta
        x = x0 + V*y
        println("x[$i] = $x")
        if la.norm(x - x0) < tol
            break
        end
        # updating for next step
        x0 = copy(x)
    end
end

restarted_FOM (generic function with 2 methods)

In [12]:
restarted_FOM(A, b, x0)

x[0] = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
x[1] = [2.9629446965789126, 0.9363238156323809, 0.2829778642800082, 0.8655793495623784, 0.499372701670603, 0.19558764148765254]
x[2] = [0.9999999999999978, 1.9999999999999996, 0.9999999999999998, 1.9999999999999996, 0.9999999999999998, 2.0]


In [13]:
function incomplete_orthogonalization_process(A:: Matrix{Float64}, b:: Vector{Float64}, x0:: Vector{Float64})
    n, m = size(A)
    r0 = b - A*x0
    beta = la.norm(r0)
    k = 2
    V = zeros((m, m+1))
    H = zeros((m+1, m))
    
    V[:, 1] = r0/beta

    for j=1:m
        w = A*V[:, j]
        for i = max(1, j - k + 1):j
            H[i, j] = la.dot(w, V[:, i])
            w = w - H[i, j]*V[:, i] 
        end
        H[j+1, j] = la.norm(w)
        V[:, j+1] = w/H[j+1, j]
    end
    H[1:m, :], V[:, 1:m], beta
end

incomplete_orthogonalization_process (generic function with 1 method)

In [14]:
H, V = incomplete_orthogonalization_process(A, b, x0)
display(H)
display(V)

6×6 Matrix{Float64}:
 4.67327  2.21877   0.0       0.0           0.0       0.0
 2.21877  3.35573   0.690815  0.0           0.0       0.0
 0.0      0.690815  4.32887   0.217999      0.0       0.0
 0.0      0.0       0.217999  3.64213      -0.227226  0.0
 0.0      0.0       0.0       9.43428e-15   2.34609   1.59463
 0.0      0.0       0.0       0.0           1.60734   5.24397

6×6 Matrix{Float64}:
  0.0       -0.493309   -0.238968  -0.446699  -0.329503   -0.0654149
  0.497519  -0.0612751   0.7893    -0.354578  -0.447183    0.368301
  0.0       -0.493309   -0.238968  -0.446699  -0.329503   -0.0727362
  0.597022  -0.0914687  -0.272545   0.246814  -0.0941437   0.611587
 -0.199007  -0.702       0.337983   0.59444   -0.75315    -0.302903
  0.597022  -0.0914687  -0.272545   0.246814  -0.0823757   0.623696

### DIOM

In [15]:
function DIOM(A:: Matrix{Float64}, b:: Vector{Float64}, x0:: Vector{Float64}, tol=1.0e-6)
    n, M = size(A)
    k = 2

    V = zeros((M, M+1))
    H = zeros((M+1, M))
    P = zeros((M, M))
    
    r0 = b - A*x0
    beta = la.norm(r0)
    zeta = beta
    V[:, 1] = r0/beta

    println("x[0] = $x0")
    for m=1:MAX_ITER
        w = A*V[:, m]
        for i = max(1, m - k + 1):m
            H[i, m] = la.dot(w, V[:, i])
            w = w - H[i, m]*V[:, i] 
        end
        H[m+1, m] = la.norm(w)
        V[:, m+1] = w/H[m+1, m]
        L, U = la.lu(H[1:m, 1:m])
        if U[m ,m] == 0
            break
        end
        if m > 1
            zeta = -L[m, m-1]*zeta  
        end
        i = m-k+1
        sum = i > 0 ? P[:, i:m-1]*U[i:m-1, m] : zeros(M)
        P[:, m] = 1/U[m, m]*(V[:, m] - sum)
        x = x0 + zeta*P[:, m]
        println("x[$m] = $x")
        if la.norm(x - x0) < tol
            break
        end
        # updating for next step
        x0 = copy(x)
    end
end

DIOM (generic function with 2 methods)

In [16]:
DIOM(A, b, x0)

x[0] = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
x[1] = [0.0, 1.069915254237288, 0.0, 1.2838983050847455, -0.4279661016949152, 1.2838983050847455]
x[2] = [1.0223756706686236, 1.6864518923080625, 1.0223756706686236, 2.0609195678848975, 0.8310997762432935, 2.0609195678848975]
x[3] = [0.9907832820475928, 1.99163513765398, 0.9907832820475928, 2.0053245062998073, 1.0118246060372202, 2.0053245062998073]
x[4] = [1.0, 2.0, 1.0, 1.9999999999999998, 1.0000000000000002, 1.9999999999999998]
x[5] = [1.0, 2.0, 1.0, 1.9999999999999998, 1.0000000000000002, 1.9999999999999998]


## The Generalized Minimum Residual Method (GMRES)
¡Por corregir!

In [17]:
# ¡Por corregir!
function s(i, H)
    return H[i+1, i]/sqrt(H[i, i]^2 + H[i+1, i]^2)
end

function c(i, H)
    return H[i, i]/sqrt(H[i, i]^2 + H[i+1, i]^2)
end

function omega(H, i, j)
    m = size(H)[2]
    if H[j, j] != 0
        t = H[i, j]/H[j, j]
        hyp = sqrt(t^2 + 1)
        s = t/hyp
        c = 1/hyp
    else
        s = 1
        c = 0
    end
    G = Matrix{Float64}(la.I, m, m)
    G[j, j] = c
    G[j, i] = s
    G[i, j] = -s
    G[i, i] = c
    return G
end

function DQGMRES(A:: Matrix{Float64}, b:: Vector{Float64}, x0:: Vector{Float64}, tol=1.0e-6)
    n, M = size(A)
    k = 2

    V = zeros((M, M+1))
    H = zeros((M+1, M))
    P = zeros((M, M))
    gamma = zeros(M)

    r0 = b - A*x0
    gamma[1] = la.norm(r0)
    V[:, 1] = r0/gamma[1]

    for m=1:MAX_ITER
        w = A*V[:, m]
        for i = max(1, m - k + 1):m
            H[i, m] = la.dot(w, V[:, i])
            w = w - H[i, m]*V[:, i] 
        end
        H[m+1, m] = la.norm(w)
        V[:, m+1] = w/H[m+1, m]
        
        Qm = Matrix{Float64}(la.I, m, m)
        for i = m-k:m-1
            if m-k>0
                Qm = omega(H[1:m,1:m], i, m)*Qm
            end
        end
        H[1:m, 1:m] = Qm*H[1:m, 1:m]

        s_m = s(m, H)
        c_m = c(m, H)

        gamma[m + 1] = -s_m*gamma[m]
        gamma[m] = c_m*gamma[m]
        H[m, m] = c_m*H[m, m] + s_m*H[m+1, m]
        i = m - k + 1
        sum = i > 0 ? P[:, i:m-1]*H[i:m-1, m] : zeros(M)
        
        P[:, m] = (V[:, m] - sum)/H[m, m]
        x = x0 + gamma[m]*P[:, m]
        
        if la.norm(x - x0) < tol
            return x
        end
        # updating for next step
        x0 = copy(x)
    end
    x
end

DQGMRES (generic function with 2 methods)

In [18]:
x = DQGMRES(A, b, x0)
x

6-element Vector{Float64}:
 0.5659042503698762
 1.3718480345450763
 0.5659042503698762
 1.4191446575475546
 0.4704325482149116
 1.4191446575475546