## Arnoldi's methods

In [54]:
import LinearAlgebra
const la = LinearAlgebra
MAX_ITER = 100;

In [55]:
A = [4. -1 0 -1 0 0;
     -1 4 -1 0 -1 0;
     0 -1 4. 0 0 -1;
     -1 0 0. 4 -1 0;
     0 -1 0 -1 4 -1;
     0 0 -1 0. -1 4]

b = [0, 5, 0, 6, -2, 6.]

x0 = zeros(size(b));
# m
v = [1., 0, 2, 0, 1, 1];

### Arnoldi
Input: $A\in\mathbb{R}^{n\times n}=[a_1,...,a_n], v\in\mathbb{R}^{n}$ any vector

In [56]:
function arnoldi(A:: Matrix{Float64}, v:: Vector{Float64})
    # input: A
    n, m = size(A)
    V = zeros((n, m + 1))
    H = zeros((m + 1, m))
    V[:, 1] = v/la.norm(v)
    for j = 1:m
        for i = 1:j
            H[i, j] = la.dot(A*V[:, j], V[:, i])
        end
        w = A*V[:, j] - V[:, 1:j]*H[1:j, j]
        H[j+1, j] = la.norm(w)
        if H[j+1, j] == 0.0
            break
        end
        V[:, j+1] = w/H[j+1, j]
    end
    H[1:m, :], V[:, 1:m]
end

arnoldi (generic function with 1 method)

In [57]:
H, V = arnoldi(A, v);
display(H)
display(V)

6×6 Matrix{Float64}:
 3.14286  1.92195  -2.77556e-15  1.3628e-14   -4.20552e-13  2.95582
 1.92195  4.6472    1.18932      1.21569e-14  -3.72813e-13  2.61937
 0.0      1.18932   3.95556      0.812257     -2.72227e-13  1.91409
 0.0      0.0       0.812257     3.67305       0.114091     0.726769
 0.0      0.0       0.0          0.114091      3.58133      0.027598
 0.0      0.0       0.0          0.0           5.08975e-13  3.76061

6×6 Matrix{Float64}:
 0.377964   0.168563    0.289595   -0.585252    0.390312   0.413137
 0.0       -0.786629    0.191845    0.228787    0.540433   0.0436258
 0.755929   0.140469   -0.282287    0.128662    0.2502     0.581096
 0.0       -0.393314    0.0959226  -0.699892   -0.310248  -0.0562773
 0.377964  -0.0280939   0.750937    0.313906   -0.440352   0.692342
 0.377964  -0.421408   -0.475959    0.0140224  -0.45036    0.0850704

### Arnoldi-Modified Gram-Schmidt

In [58]:
function arnoldi_modified(A:: Matrix{Float64}, v:: Vector{Float64})
    n, m = size(A)
    
    V = zeros((n, m + 1))
    H = zeros((m + 1, m))
    
    v = v/la.norm(v)
    V[:, 1] = v/la.norm(v)
    for j = 1:m
        w = A*V[:, j]
        for i = 1:j
            H[i, j] = la.dot(w, V[:, i])
            w = w - H[i, j]*V[:, i] 
        end
        H[j+1, j] = la.norm(w)
        if H[j+1, j] == 0.0
            break
        end
        V[:, j+1] = w/H[j+1, j]
    end
    H[1:m, :], V[:, 1:m]
end

arnoldi_modified (generic function with 1 method)

In [59]:
H, V = arnoldi_modified(A, v);
display(H)
display(V)

6×6 Matrix{Float64}:
 3.14286  1.92195  7.43849e-15  -3.19189e-14  9.71667e-13  -3.59742
 1.92195  4.6472   1.18932      -3.16414e-14  9.67726e-13  -3.58099
 0.0      1.18932  3.95556       0.812257     2.44915e-13  -0.907632
 0.0      0.0      0.812257      3.67305      0.114091     -0.14671
 0.0      0.0      0.0           0.114091     3.58133      -0.00211734
 0.0      0.0      0.0           0.0          9.66097e-13   4.29368e-5

6×6 Matrix{Float64}:
 0.377964   0.168563    0.289595   -0.585252    0.390312  -0.435541
 0.0       -0.786629    0.191845    0.228787    0.540433   0.254659
 0.755929   0.140469   -0.282287    0.128662    0.2502    -0.719964
 0.0       -0.393314    0.0959226  -0.699892   -0.310248   0.136983
 0.377964  -0.0280939   0.750937    0.313906   -0.440352  -0.433932
 0.377964  -0.421408   -0.475959    0.0140224  -0.45036   -0.141579

### Householder Arnoldi

In [ ]:
function householder_arnoldi()
    
end

## Arnoldi’s Method for Linear Systems (FOM)

In [60]:
function FOM(A:: Matrix{Float64}, b:: Vector{Float64}, x0:: Vector{Float64})
    n, m = size(A)
    r0 = b - A*x0
    beta = la.norm(r0)
    V = zeros((m, m+1))
    H = zeros((m+1, m))

    V[:, 1] = r0/beta
    for j=1:m
        w = A*V[:, j]
        for i=1:j
            H[i, j] = la.dot(w, V[:, i])
            w = w - H[i, j]*V[:, i]
        end
        H[j+1, j] = la.norm(w)
        if H[j+1, j] == 0.0
            m = j
            break
        end
        V[:, j+1] = w/H[j+1, j]
    end
    H[1:m, :], V[:, 1:m], beta
end

FOM (generic function with 1 method)

In [61]:
function e_vector(n:: Int64, k:: Int64)
    e = zeros(n)
    e[k] = 1
    return e
end

e_vector (generic function with 1 method)

In [62]:
H, V, beta = FOM(A, b, x0)
y = la.inv(H)*beta*e_vector(size(H)[1], 1)
x = x0 + V*y

6-element Vector{Float64}:
 0.9999999999999929
 2.000000000000032
 0.9999999999999929
 2.0
 1.0
 2.0

In [63]:
function restarted_FOM(A:: Matrix{Float64}, b:: Vector{Float64}, x0:: Vector{Float64})
    n, m = size(A)
    r0 = b - A*x0
    beta = la.norm(r0)
    v = r0/beta
    
    V = zeros((m, m+1))
    W = zeros((m, m))
    H = zeros((m+1, m))

    H, V = arnoldi(A, v)
    y = la.inv(H)*beta*e_vector(size(H)[1], 1)
    x = x0 + V*y
    return x
end

restarted_FOM (generic function with 1 method)

In [64]:
x = restarted_FOM(A, b, x0)


6-element Vector{Float64}:
 1.0000000000000007
 1.9999999999999996
 1.0000000000000007
 2.0
 1.0000000000000007
 2.0

In [65]:
function incomplete_orthogonalization_process(A:: Matrix{Float64}, b:: Vector{Float64}, x0:: Vector{Float64})
    n, m = size(A)
    r0 = b - A*x0
    beta = la.norm(r0)
    k = 2
    V = zeros((m, m+1))
    H = zeros((m+1, m))
    
    V[:, 1] = r0/beta

    for j=1:m
        w = A*V[:, j]
        for i = max(1, j - k + 1):j
            H[i, j] = la.dot(w, V[:, i])
            w = w - H[i, j]*V[:, i] 
        end
        H[j+1, j] = la.norm(w)
        V[:, j+1] = w/H[j+1, j]
    end
    H[1:m, :], V[:, 1:m], beta
end

incomplete_orthogonalization_process (generic function with 1 method)

In [66]:
H, V = incomplete_orthogonalization_process(A, b, x0)
display(H)
display(V)

6×6 Matrix{Float64}:
 4.67327  2.21877   0.0       0.0           0.0       0.0
 2.21877  3.35573   0.690815  0.0           0.0       0.0
 0.0      0.690815  4.32887   0.217999      0.0       0.0
 0.0      0.0       0.217999  3.64213      -0.227226  0.0
 0.0      0.0       0.0       9.43428e-15   2.34609   1.59463
 0.0      0.0       0.0       0.0           1.60734   5.24397

6×6 Matrix{Float64}:
  0.0       -0.493309   -0.238968  -0.446699  -0.329503   -0.0654149
  0.497519  -0.0612751   0.7893    -0.354578  -0.447183    0.368301
  0.0       -0.493309   -0.238968  -0.446699  -0.329503   -0.0727362
  0.597022  -0.0914687  -0.272545   0.246814  -0.0941437   0.611587
 -0.199007  -0.702       0.337983   0.59444   -0.75315    -0.302903
  0.597022  -0.0914687  -0.272545   0.246814  -0.0823757   0.623696

### DIOM

In [67]:
function DIOM(A:: Matrix{Float64}, b:: Vector{Float64}, x0:: Vector{Float64}, tol=1.0e-6)
    n, M = size(A)
    k = 2

    V = zeros((M, M+1))
    H = zeros((M+1, M))
    P = zeros((M, M))
    
    r0 = b - A*x0
    beta = la.norm(r0)
    zeta = beta
    V[:, 1] = r0/beta
    for m=1:MAX_ITER
        w = A*V[:, m]
        for i = max(1, m - k + 1):m
            H[i, m] = la.dot(w, V[:, i])
            w = w - H[i, m]*V[:, i] 
        end
        H[m+1, m] = la.norm(w)
        V[:, m+1] = w/H[m+1, m]
        L, U = la.lu(H[1:m, 1:m])
        if U[m ,m] == 0
            break
        end
        if m > 1
            zeta = -L[m, m-1]*zeta  
        end
        i = m-k+1
        sum = i > 0 ? P[:, i:m-1]*U[i:m-1, m] : zeros(M)
        P[:, m] = 1/U[m, m]*(V[:, m] - sum)
        x = x0 + zeta*P[:, m]
        if la.norm(x - x0) < tol
            return x
        end
        # updating for next step
        x0 = copy(x)
    end
    x
end

DIOM (generic function with 2 methods)

In [68]:
x = DIOM(A, b, x0)
x

6-element Vector{Float64}:
 1.0
 2.0
 1.0
 1.9999999999999998
 1.0000000000000002
 1.9999999999999998

## The Generalized Minimum Residual Method (GMRES)
¡Por corregir!

In [107]:
# ¡Por corregir!
function s(i, H)
    return H[i+1, i]/sqrt(H[i, i]^2 + H[i+1, i]^2)
end

function c(i, H)
    return H[i, i]/sqrt(H[i, i]^2 + H[i+1, i]^2)
end

function omega(H, i, j)
    m = size(H)[2]
    if H[j, j] != 0
        t = H[i, j]/H[j, j]
        hyp = sqrt(t^2 + 1)
        s = t/hyp
        c = 1/hyp
    else
        s = 1
        c = 0
    end
    G = Matrix{Float64}(la.I, m, m)
    G[j, j] = c
    G[j, i] = s
    G[i, j] = -s
    G[i, i] = c
    return G
end

function DQGMRES(A:: Matrix{Float64}, b:: Vector{Float64}, x0:: Vector{Float64}, tol=1.0e-6)
    n, M = size(A)
    k = 2

    V = zeros((M, M+1))
    H = zeros((M+1, M))
    P = zeros((M, M))
    gamma = zeros(M)

    r0 = b - A*x0
    gamma[1] = la.norm(r0)
    V[:, 1] = r0/gamma[1]

    for m=1:MAX_ITER
        w = A*V[:, m]
        for i = max(1, m - k + 1):m
            H[i, m] = la.dot(w, V[:, i])
            w = w - H[i, m]*V[:, i] 
        end
        H[m+1, m] = la.norm(w)
        V[:, m+1] = w/H[m+1, m]
        
        Qm = Matrix{Float64}(la.I, m, m)
        for i = m-k:m-1
            if m-k>0
                Qm = omega(H[1:m,1:m], i, m)*Qm
            end
        end
        H[1:m, 1:m] = Qm*H[1:m, 1:m]

        s_m = s(m, H)
        c_m = c(m, H)

        gamma[m + 1] = -s_m*gamma[m]
        gamma[m] = c_m*gamma[m]
        H[m, m] = c_m*H[m, m] + s_m*H[m+1, m]
        i = m - k + 1
        sum = i > 0 ? P[:, i:m-1]*H[i:m-1, m] : zeros(M)
        
        P[:, m] = (V[:, m] - sum)/H[m, m]
        x = x0 + gamma[m]*P[:, m]
        
        if la.norm(x - x0) < tol
            return x
        end
        # updating for next step
        x0 = copy(x)
    end
    x
end

DQGMRES (generic function with 2 methods)

In [108]:
x = DQGMRES(A, b, x0)
x

6-element Vector{Float64}:
 0.5659042503698762
 1.3718480345450763
 0.5659042503698762
 1.4191446575475546
 0.4704325482149116
 1.4191446575475546